package com.sere.filemanager.phone

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.activity.compose.setContent
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.sere.filemanager.core.model.*
import com.sere.filemanager.core.ui.FileManagerTheme
import com.sere.filemanager.core.ui.UiFormatters

class MainActivity : ComponentActivity() { override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); setContent { PhoneFileManagerApp() } } }

@Composable fun PhoneFileManagerApp() {
    val context = LocalContext.current
    val viewModel: PhoneViewModel = viewModel(factory = PhoneViewModelFactory(context))
    val filePicker = rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()) { uri -> if (uri != null) viewModel.onPickedFile(uri) }
    val treePicker = rememberLauncherForActivityResult(ActivityResultContracts.OpenDocumentTree()) { uri -> viewModel.addStorageTree(uri) }
    val permissionLauncher = rememberLauncherForActivityResult(ActivityResultContracts.RequestMultiplePermissions()) { results -> viewModel.onPermissionsResult(results) }
    val permissionActions = remember(permissionLauncher) { PhonePermissionActions(permissionLauncher) }
    val screen = remember { mutableStateOf(PhoneScreen.Home) }
    val state by viewModel.state.collectAsState()
    val selected = state.fileActions.selected
    val selectedMedia = state.media.selected
    BackHandler(enabled = screen.value != PhoneScreen.Home) { screen.value = PhoneScreen.Home }
    FileManagerTheme { when (screen.value) {
        PhoneScreen.Home -> PhoneHomeScreen(state.statusMessage, { screen.value = PhoneScreen.PhoneStorageRoots }, { screen.value = PhoneScreen.PhoneFiles }, { screen.value = PhoneScreen.PhoneMedia }, { screen.value = PhoneScreen.StorageAnalyzer }, { screen.value = PhoneScreen.WatchCompanion }, { screen.value = PhoneScreen.RemoteManager }, { screen.value = PhoneScreen.RemoteSettings }, { screen.value = PhoneScreen.Settings })
        PhoneScreen.PhoneStorageRoots -> PhoneStorageRootsScreen(state.storageRoots, { root -> viewModel.selectStorageRoot(root); screen.value = PhoneScreen.PhoneFiles }, { treePicker.launch(null) }) { screen.value = PhoneScreen.Home }
        PhoneScreen.PhoneFiles -> PhoneFilesScreen(state.browser, state.clipboard, state.operationProgress, { path, type -> if (type == FileItemType.Directory) viewModel.openPhoneItem(path, type) else { viewModel.selectPhoneFile(path); screen.value = PhoneScreen.PhoneFileActions } }, viewModel::phoneGoUp, { viewModel.beginCreateFolder(); screen.value = PhoneScreen.PhoneCreateFolder }, viewModel::pasteClipboardHere, viewModel::clearClipboard) { screen.value = PhoneScreen.Home }
        PhoneScreen.PhoneFileActions -> selected?.let { PhoneFileActionScreen(it, { screen.value = PhoneScreen.PhoneFileDetails }, { viewModel.beginRenameSelected(); screen.value = PhoneScreen.PhoneRenameFile }, { viewModel.markSelectedForCopy(); screen.value = PhoneScreen.PhoneFiles }, { viewModel.markSelectedForMove(); screen.value = PhoneScreen.PhoneFiles }, { viewModel.copySelectedPhoneFile(); screen.value = PhoneScreen.PhoneFiles }, { sharePhoneFile(context, it, viewModel) }, { viewModel.toggleFavoriteSelectedPhoneFile() }, { screen.value = PhoneScreen.PhoneConfirmDelete }, { screen.value = PhoneScreen.PhoneFiles }) } ?: run { screen.value = PhoneScreen.PhoneFiles }
        PhoneScreen.PhoneRenameFile -> PhoneRenameFileScreen(state.edit.renameValue, viewModel::updateRenameValue, { viewModel.renameSelectedFromInput(); screen.value = PhoneScreen.PhoneFiles }, { screen.value = PhoneScreen.PhoneFileActions })
        PhoneScreen.PhoneCreateFolder -> PhoneCreateFolderScreen(state.edit.createFolderValue, viewModel::updateCreateFolderName, { viewModel.createFolderFromInput(); screen.value = PhoneScreen.PhoneFiles }, { screen.value = PhoneScreen.PhoneFiles })
        PhoneScreen.PhoneFileDetails -> selected?.let { PhoneFileDetailsScreen(it) { screen.value = PhoneScreen.PhoneFileActions } } ?: run { screen.value = PhoneScreen.PhoneFiles }
        PhoneScreen.PhoneConfirmDelete -> selected?.let { PhoneConfirmDeleteScreen(it.name, { viewModel.deleteSelectedPhoneFile(); screen.value = PhoneScreen.PhoneFiles }, { screen.value = PhoneScreen.PhoneFileActions }) } ?: run { screen.value = PhoneScreen.PhoneFiles }
        PhoneScreen.PhoneMedia -> { LaunchedEffect(Unit) { if (state.media.items.isEmpty()) viewModel.loadPhoneMedia() }; PhoneMediaLibraryScreen(state.media, viewModel::loadPhoneMedia, permissionActions::requestMedia, { item -> if (item.mimeType?.startsWith("image/") == true) { viewModel.openImagePreview(item); screen.value = PhoneScreen.PhoneImagePreview } else { viewModel.selectMedia(item); screen.value = PhoneScreen.PhoneMediaPreview } }) { screen.value = PhoneScreen.Home } }
        PhoneScreen.PhoneImagePreview -> PhoneImagePreviewScreen(state.imagePreview, viewModel::imageZoomToggle, viewModel::imageRotateLeft, viewModel::imageRotateRight) { screen.value = PhoneScreen.PhoneMedia }
        PhoneScreen.PhoneMediaPreview -> selectedMedia?.let { PhoneMediaPreviewScreen(it, onPlay = { screen.value = PhoneScreen.PhoneMediaPlayer }, onBack = { screen.value = PhoneScreen.PhoneMedia }) } ?: run { screen.value = PhoneScreen.PhoneMedia }
        PhoneScreen.PhoneMediaPlayer -> PhonePlaybackControls(state.playback, viewModel::playbackPlayPause, viewModel::playbackSeekBack, viewModel::playbackSeekForward, viewModel::playbackStop, notification = state.mediaSession.notification) { screen.value = PhoneScreen.PhoneMediaPreview }
        PhoneScreen.StorageAnalyzer -> PhoneStorageAnalyzerScreen(state.analyzer, viewModel::analyzeCurrentPhoneFolder) { screen.value = PhoneScreen.Home }
        PhoneScreen.WatchCompanion -> WatchCompanionScreen(state.remoteUrl, state.statusMessage, state.transfer, viewModel::setRemoteUrl, viewModel::setTransferTargetPath, viewModel::startPairing, viewModel::startRemoteServer, viewModel::stopRemoteServer, viewModel::requestWatchStatus, viewModel::refreshRemoteSnapshot, viewModel::refreshTransferProgress, { filePicker.launch(arrayOf("*/*")) }) { screen.value = PhoneScreen.Home }
        PhoneScreen.RemoteManager -> RemoteManagerScreen(state.remoteUrl, state.statusMessage, viewModel::setRemoteUrl, { openRemoteManagerInBrowser(context, state.remoteUrl, viewModel) }) { screen.value = PhoneScreen.Home }
        PhoneScreen.RemoteSettings -> RemoteSettingsScreen(state.remoteSettings, viewModel::toggleUploads, viewModel::toggleDelete, viewModel::toggleRequirePin, viewModel::toggleLocalNetworkOnly, viewModel::setRemotePort, viewModel::setRemoteAutoStop, viewModel::toggleSettingsAdvanced, viewModel::toggleShowHidden, viewModel::syncSettingsToWatch) { screen.value = PhoneScreen.Home }
        PhoneScreen.Settings -> PhoneSettingsScreen(state.appSettings, viewModel::toggleSettingsHidden, viewModel::toggleSettingsAdvanced, viewModel::toggleSettingsBattery, viewModel::toggleSettingsHaptics) { screen.value = PhoneScreen.Home }
    } }
}

@Composable private fun PhoneHomeScreen(status: String, onRoots: () -> Unit, onFiles: () -> Unit, onMedia: () -> Unit, onAnalyzer: () -> Unit, onWatch: () -> Unit, onRemote: () -> Unit, onRemoteSettings: () -> Unit, onSettings: () -> Unit) { Column(modifier = Modifier.fillMaxSize().padding(24.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) { Text("FileManager", style = MaterialTheme.typography.headlineMedium); Text(status); HomeButton("Storage", "Storage roots", "Choose phone storage location", onRoots); HomeButton("Files", "Phone files", DefaultHomeActions.files.description, onFiles); HomeButton("Media", "Phone media", DefaultHomeActions.media.description, onMedia); HomeButton("Analyze", "Storage analyzer", DefaultHomeActions.analyzer.description, onAnalyzer); HomeButton("Watch", "Watch companion", "Optional Wear OS helper", onWatch); HomeButton("Remote", "Remote manager", "Open watch/phone server tools", onRemote); HomeButton("Security", "Remote settings", "Sync watch server permissions", onRemoteSettings); HomeButton("Settings", "Settings", DefaultHomeActions.settings.description, onSettings) } }
@Composable private fun HomeButton(icon: String, title: String, subtitle: String, onClick: () -> Unit) { Card(modifier = Modifier.fillMaxWidth().clickable(onClick = onClick)) { Row(modifier = Modifier.fillMaxWidth().padding(16.dp), horizontalArrangement = Arrangement.spacedBy(12.dp), verticalAlignment = Alignment.CenterVertically) { Text(icon, style = MaterialTheme.typography.titleSmall); Column { Text(title, style = MaterialTheme.typography.titleMedium); Text(subtitle, style = MaterialTheme.typography.bodyMedium) } } } }
@Composable private fun PhoneFilesScreen(browser: PhoneFileBrowserState, clipboard: PhoneClipboardState, operationProgress: PhoneOperationProgressState, onOpen: (String, FileItemType) -> Unit, onUp: () -> Unit, onCreateFolder: () -> Unit, onPaste: () -> Unit, onClearClipboard: () -> Unit, onBack: () -> Unit) { Column(modifier = Modifier.fillMaxSize().padding(24.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { Text("Phone files", style = MaterialTheme.typography.headlineSmall); Text(browser.currentPath, maxLines = 1, overflow = TextOverflow.Ellipsis); Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { Button(onClick = onUp) { Text("Up") }; Button(onClick = onCreateFolder) { Text("New folder") }; Button(onClick = onBack) { Text("Home") } }; if (operationProgress.visible) PhoneOperationProgressCard(operationProgress.current); if (clipboard.hasEntry) Card(modifier = Modifier.fillMaxWidth()) { Column(modifier = Modifier.padding(12.dp)) { Text("Clipboard: ${clipboard.mode} ${clipboard.fileName}"); clipboard.message?.let { Text(it) }; Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { Button(onClick = onPaste) { Text("Paste here") }; Button(onClick = onClearClipboard) { Text("Clear") } } } }; browser.error?.let { Text(it) }; if (browser.isLoading) Text("Loading…"); if (!browser.isLoading && browser.items.isEmpty()) Text("Empty folder"); LazyColumn(verticalArrangement = Arrangement.spacedBy(6.dp)) { items(browser.items) { item -> PhoneFileRow(item, onOpen) } } } }
@Composable private fun PhoneFileRow(item: FileItem, onOpen: (String, FileItemType) -> Unit) { val icon = when (item.type) { FileItemType.Directory -> "DIR"; FileItemType.Image -> "IMG"; FileItemType.Video -> "VID"; FileItemType.Audio -> "AUD"; FileItemType.Archive -> "ZIP"; FileItemType.Document -> "DOC"; FileItemType.Other -> "FILE" }; Card(modifier = Modifier.fillMaxWidth().clickable { onOpen(item.path, item.type) }) { Row(modifier = Modifier.fillMaxWidth().padding(12.dp), horizontalArrangement = Arrangement.spacedBy(10.dp), verticalAlignment = Alignment.CenterVertically) { Text(icon); Column(modifier = Modifier.weight(1f)) { Text(item.name, maxLines = 1, overflow = TextOverflow.Ellipsis); Text(UiFormatters.compactBytes(item.sizeBytes)) } } } }
@Composable private fun WatchCompanionScreen(remoteUrl: String, status: String, transfer: PhoneTransferState, onUrl: (String) -> Unit, onTargetPath: (String) -> Unit, onPair: () -> Unit, onStart: () -> Unit, onStop: () -> Unit, onStatus: () -> Unit, onSnapshot: () -> Unit, onTransferRefresh: () -> Unit, onSend: () -> Unit, onBack: () -> Unit) { Column(modifier = Modifier.fillMaxSize().padding(24.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) { Text("Watch companion", style = MaterialTheme.typography.headlineSmall); Text(status); PhoneTransferStatusCard(transfer, onTransferRefresh); OutlinedTextField(value = remoteUrl, onValueChange = onUrl, label = { Text("Watch HTTP URL") }, modifier = Modifier.fillMaxWidth()); OutlinedTextField(value = transfer.targetPath, onValueChange = onTargetPath, label = { Text("Watch target folder") }, modifier = Modifier.fillMaxWidth()); Button(onClick = onPair, modifier = Modifier.fillMaxWidth()) { Text("Find watch") }; Button(onClick = onStart, modifier = Modifier.fillMaxWidth()) { Text("Start watch server") }; Button(onClick = onStop, modifier = Modifier.fillMaxWidth()) { Text("Stop watch server") }; Button(onClick = onStatus, modifier = Modifier.fillMaxWidth()) { Text("Ask status") }; Button(onClick = onSnapshot, modifier = Modifier.fillMaxWidth()) { Text("Refresh watch status") }; Button(onClick = onSend, enabled = !transfer.isSending, modifier = Modifier.fillMaxWidth()) { Text(if (transfer.isSending) "Sending…" else "Choose and send file") }; Button(onClick = onBack) { Text("Home") } } }
@Composable private fun RemoteManagerScreen(remoteUrl: String, status: String, onUrl: (String) -> Unit, onOpen: () -> Unit, onBack: () -> Unit) { Column(modifier = Modifier.fillMaxSize().padding(24.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) { Text("Remote manager", style = MaterialTheme.typography.headlineSmall); Text(status); OutlinedTextField(value = remoteUrl, onValueChange = onUrl, label = { Text("Server URL") }, modifier = Modifier.fillMaxWidth()); Button(onClick = onOpen, modifier = Modifier.fillMaxWidth()) { Text("Open in browser") }; Button(onClick = onBack) { Text("Home") } } }
private fun openRemoteManagerInBrowser(context: Context, url: String, viewModel: PhoneViewModel) { val trimmed = url.trim(); if (trimmed.isBlank() || !(trimmed.startsWith("http://") || trimmed.startsWith("https://"))) { viewModel.openRemoteManager(); return }; runCatching { context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(trimmed))) }.onFailure { viewModel.openRemoteManager() } }
private fun sharePhoneFile(context: Context, item: FileItem, viewModel: PhoneViewModel) { val uri = Uri.parse(item.path); runCatching { val intent = Intent(Intent.ACTION_SEND).apply { type = "*/*"; putExtra(Intent.EXTRA_STREAM, uri); addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION) }; context.startActivity(Intent.createChooser(intent, "Share ${item.name}")) }.onSuccess { viewModel.markPhoneFileShared(item.name) }.onFailure { viewModel.markPhoneShareFailed(it.message ?: "Share failed") } }
